export { Tabs } from './namespace'
export { default as TabsContent } from './TabsContent.vue'
export { default as TabsIndicator } from './TabsIndicator.vue'
export { default as TabsList } from './TabsList.vue'
export { default as TabsRoot } from './TabsRoot.vue'
export { default as TabsTrigger } from './TabsTrigger.vue'
export * from './types'
export { listVariant, tabsListVariants, tabsTriggerVariants, triggerVariant } from './variant'
