export { default as AvatarFallback } from './AvatarFallback.vue'
export { default as AvatarGroup } from './AvatarGroup.vue'
export { default as AvatarImage } from './AvatarImage.vue'
export { default as AvatarRoot } from './AvatarRoot.vue'
export { Avatar } from './namespace'
