export { TagsInput } from './namespace'
export { default as TagsInputControl } from './TagsInputControl.vue'
export { default as TagsInputInput } from './TagsInputInput.vue'
export { default as TagsInputItem } from './TagsInputItem.vue'
export { default as TagsInputItemDelete } from './TagsInputItemDelete.vue'
export { default as TagsInputItemInput } from './TagsInputItemInput.vue'
export { default as TagsInputItemPreview } from './TagsInputItemPreview.vue'
export { default as TagsInputItemText } from './TagsInputItemText.vue'
export { default as TagsInputRoot } from './TagsInputRoot.vue'
export { useTagsInput } from '@ark-ui/vue/tags-input'
